export type { TypeGuard } from '@accuser/unist-util-type-guards';
export { default as isComment } from './is-comment.js';
export { default as isDoctype } from './is-doctype.js';
export { default as isElement } from './is-element.js';
export { default as isLiteral } from './is-literal.js';
export { default as isMonoparous } from './is-monoparous.js';
export { default as isMultiparous } from './is-multiparous.js';
export { default as isNode } from './is-node.js';
export { default as isNulliparous } from './is-nulliparous.js';
export { default as isParent } from './is-parent.js';
export { default as isRoot } from './is-root.js';
export { default as isText } from './is-text.js';
